# Include Conan toolchain file if available
if(DEFINED ENV{CONAN_PROFILES_DIR})
    message(STATUS "Using Conan profiles directory from environment variable: $ENV{CONAN_PROFILES_DIR}.")
    set(CONAN_TOOLCHAIN_FILE "$ENV{CONAN_PROFILES_DIR}")
else()
    message(STATUS "Using Conan profiles directory from project configuration.")
    set(CONAN_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/conan-profiles")
endif()

set(CONAN_TOOLCHAIN_FILE "${CONAN_TOOLCHAIN_FILE}/${CONAN_INSTALL_DIR}/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
if(EXISTS ${CONAN_TOOLCHAIN_FILE})
    include(${CONAN_TOOLCHAIN_FILE})
else()
    message(WARNING "Skipping Conan integration. Path ${CONAN_TOOLCHAIN_FILE} does not exist.")
endif()
